#!/bin/sh 
#
# Ramdisk init process for booting Mer on Xperia acro S
# Copyright (C) 2012 Marko Saukko
# Copyright (C) 2013 BPaul
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# IRC: Sage @ #mer & #nemomobile @ Freenode

echo "
#######################################################################
#                                                                     #
#            WELCOME TO LINUX LOADER ON THE XPERIA ACRO S             #
#                               v0.1                                  #
#                                                                     #
#                    Paul Rich (BPaul), May 18th 2013                 #
#                                                                     #
#######################################################################
"

echo "Creating directories..."
mkdir -p /proc
mkdir -p /sys
mkdir -p /dev
mkdir -p /mnt

echo "Mounting base..."
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs devtmpfs /dev

wait 5
echo "List dirs"
mkdir -p /sdpart
mount /dev/mmcblk0p14 /sdpart
echo "List mmcblk0p14"
cd /sdpart
ls
wait 5
echo "List dirs"

echo "List dirs"
echo "List dirs"

wait 5


#LOOP_DEV="/dev/loop0"
#SD_DEV="/dev/mmcblk0p14"
#SD_PART="/sdpart"
#IMAGE="${SD_PART}/mer.img"
#ROOTFSMNTDIR="/mnt"
#INITBIN="/sbin/init"

#echo "Mounting..."
#mkdir -p ${SD_PART}
#mount ${SD_DEV} ${SD_PART}

#echo "Booting image..."
#losetup ${LOOP_DEV} ${IMAGE}
#mount ${LOOP_DEV} ${ROOTFSMNTDIR}

#umount -l /dev
#umount -l /sys
#umount -l /proc

#echo "Switching to rootfs at ${ROOTFSMNTDIR}, with init ${INITBIN}..."
#exec switch_root ${ROOTFSMNTDIR} ${INITBIN}
